title: PVA Markets
description: Reliable Phone Verified Accounts for Marketing & Automation
theme: minimal-mistakes-jekyll
url: "https://pvamarkets.github.io"
logo: /assets/img/logo.png
author:
  name: PVA Markets Team
  email: contact@pvamarkets.com
  links:
    - label: Twitter
      icon: fab fa-twitter
      url: https://twitter.com/pvamarkets
    - label: LinkedIn
      icon: fab fa-linkedin
      url: https://linkedin.com/company/pvamarkets
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/pvamarkets
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
